lib/sync-settings.coffee
Don't upload the `personalAccessToken` or `gistId`. The access token is as good as a password so even if someone has locked down the token to only update Gist, they could still make changes to other Gists of the user.
Fixes #14
=> Remove sensitive sync-settings setting data

lib/sync-settings.coffee
I loved this package so much, but besides autoupdate (which i understand is in the works), I really found it irritating not to get any notification on upload/download.
With this commit will both failed and successful attempts at syncing display an `atom.notification` message appropriate to the result.
*Successes*
*Bad credential (O-Auth)*
*Non-existent Gist*
Let me know if there is anything you'd want me to change around. Thanks so much for this amazing package!
=> Added notifications feedbacks

lib/sync-settings.coffee
The `sync-settings:upload` and `sync-settings:download` commands only showed up in the command palette while inside a text editor, so not if in settings view or basically anything that isn't a text editor. With this change the commands always show up in the command palette
=> Command scope-selector 'atom-text-editor' -> 'atom-workspace'

keymaps/sync-settings.cson
The scope selector was `.atom-workspace` indicating a class, but `atom-workspace` is actually an element
=> Changed keymap scope-selector

lib/sync-settings.coffee
Converted the `configDefaults` object to a [config schema](https://atom.io/docs/api/v0.184.0/Config#config-schemas) because `configDefaults` is deprecated
=> moved away from deprecated 'configDefaults'

lib/sync-settings.coffee, spec/sync-settings-spec.coffee
Add a setting, `extraFiles`, that defines files inside the `~/.atom` directory other than Atom's default config files that should also be uploaded.
Also implements #31
=> Add setting to also upload files other than Atom's default files

lib/sync-settings.coffee
I'm not sure if "store" was a deliberate choice of wording, but my gut says "storage" is the more appropriate word.
=> String changes in sync-settings.coffee

lib/sync-settings.coffee, spec/sync-settings-spec.coffee
Changes the name of the downloaded gist file to `snippets.cson`.
F.
=> Solve issue #36 (Snippets not applied)

lib/config.coffee, lib/sync-settings.coffee
Having the config file in separate file allows for clearer separation of concerns and possible reuse.
=> :art: extract package configuration to separate file

lib/sync-settings.coffee, menus/sync-settings.cson, package.json
Currently we allow the user to open the backup gist only for a short period of time after performing backup. This PR adds a new menu option that can open the gist at any time.
=> new menu option to open the gist with external browser

README.md, lib/config.coffee, lib/sync-settings.coffee, menus/sync-settings.cson, package.json, spec/sync-settings-spec.coffee
The check is at atom start-up. Right now this adds about 500ms to startup time. With some refactoring I think it can go down to <100ms.
Dropped features from this PR:
Ref #81
=> display notification if backup is newer than last one created/used

lib/sync-settings.coffee
During conflict resolution the command implementation was removed by accident.
Ref #88
=> restore `check backup` command

lib/sync-settings.coffee
Fixes #135.
This was the only `cb` call which was not checked.
=> Check to make sure `cb` is a function.

lib/sync-settings.coffee
Currently the backup file `packages.json` contains all packages in "random" order. So even if no package has changed the backup file likely has changes due to shuffling around the entries.
In order to avoid unnecessary changes and make the diff of the backup file more readable this patch orders the list of packages alphabetically.
=> use deterministic order of packages

README.md
=> Add sync-setting for config.cson keys to README

spec/sync-settings-spec.coffee
Running the tests on Windows would cause files to be created in `C:\tmp`, rather than the OS's temp directory.
Use `path` and `os` as per [Atom's CONTRIBUTING.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md).
=> Use per-OS tmp dir

README.md, lib/fork-gistid-input-view.coffee, lib/sync-settings.coffee, package.json
After triggering the new `fork` command the user provides the Gist ID from a different GitHub user and this will fork the settings and store the new Gist ID in the configuration.
This is intended to replace #136.
=> add a fork command

lib/sync-settings.coffee
Until it is possible to prevent whitespace to be inserted into these configuration values this patch makes sure to trim the value to avoid the problem reported in #153. Fixes #153.
=> trim gist id and personal access token

lib/sync-settings.coffee
Since it makes sense to sync some of the settings of this package this patch reduces the list of blacklisted key to the ones which are either security critical or specific to a local instance.
=> reduce blacklisted key

README.md
Just added a small text because if you don't configure the gist permissions you'll get a security error.
=> Added text to explain the gist permissions you need for your token

lib/package-manager.coffee, lib/sync-settings.coffee
It looked like the `update` function in `package-manager.coffee` isn't actually being called anywhere, so I wasn't sure how to integrate changes to it. It also looked like none of the tests went that deep into whether or not a package is being synced, so I wasn't sure if a test should be written for this or how you would like it done.
Much to my dismay apm doesn't seem to accept commit refs when installing from git, so I don't believe we can guarantee a particular version, but this is working for me.
Please let me know if I missed anything in the contributing guide, or if you would like me to make any changes.
Fixes #298.
=> Allow syncing git-installed packages

lib/config.coffee, lib/sync-settings.coffee
=> Remove obsolete packages.

README.md
per https://github.com/atom-community/sync-settings/issues/317 - made it a bit easier to notice than the original copy.
=> Clarify that backup must be done manually

lib/sync-settings.coffee
This fixes a typo in the config key within the restore process which prevents this from ever executing.
=> Fix "Remove Obsolete Packages" setting

lib/sync-settings.coffee
=> use token from package settings before checking environment variable

lib/sync-settings.coffee, spec/sync-settings-spec.coffee
when Atom beta 1.25.0beta0,  `atom.config.configDirPath` seems undefined. 
resolve #401
=> Fix config path with Atom 1.25

spec/sync-settings-spec.coffee
ref: https://github.com/atom-community/sync-settings/pull/403#pullrequestreview-97902873
In my environment, both init.coffee and init.js exists. 
```
it "back up the user init.coffee file", ->
atom.config.set('sync-settings.syncInit', true)
run (cb) ->
SyncSettings.backup cb
```
this test backups init.js instead of init.coffee, so my test fails locally.
Use atom.getUserInitScriptPath() to detect what file is expected to backup.
=> Fix init script spec with Atom 1.25

lib/sync-settings.coffee
Logging the full personal access token is a security-leak hazard, even
if it's useful for debugging. So let's redact parts of it, so we have
enough to reasonably validate the API-token. Copy/paste errors are more
likely in the beginning and end than the middle.
=> redact parts of the personal access token

README.md, lib/sync-settings.coffee
Rebased version of #367 to get CI passing.
=> Utilize GIST_ID environment variable for bootstrapping a fresh install

lib/sync-settings.coffee
It seems we can get undefined returned here, which currently makes us
crash. So let's avoid trying to slice the string in that case, and just
report that there's no token instead.
Fixes #409.
=> do not crash on undefined token

lib/sync-settings.coffee, spec/sync-settings-spec.coffee
Fixes #417, #416, #413, #384, #368, #362, #315.
All of these reports are `Uncaught SyntaxError` when invoking `JSON.parse` with content retrieved from the Gist which is either the `settings.json` or `packages.json` file. I don't know if in each case the content was altered to be invalid JSON or if there is a case where this packages uploads invalid JSON.
Anyway this patch catches this problem before starting to replace any configuration in the `restore` call in case either of the files is invalid. The problem results in an `error` notification to make it visible to the user.
* The first commit adds the spec (which is expected to fail CI).
* The second commits adds the check of the input data to be valid JSON (which should then make the spec pass on CI).
=> ensure fetched files contain valid JSON before using them to restore config

README.md
I've tried to read `the official contribution guidelines of Atom`, but after clicking it, I've redirected to the index page <https://flight-manual.atom.io/>.
<https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/> looks right to me.
=> Fix a broken link in "README.md".

lib/sync-settings.js, spec/sync-settings-spec.js
This does not prevent the diff view from showing differences in package versions but only prevents the check backup call from failing if `Always Install Latest Version` is checked and the only difference is package versions.
discussion: https://github.com/atom-community/sync-settings/issues/497#issuecomment-595080704
=> fix: fix check backup with only change in package versions

lib/sync-settings.js, lib/views/diff-view.js, spec/sync-settings-spec.js
Wait for location service before performing auto check. This will prevent a race condition between the auto check and the location package loading.
If there is no location package installed it will not do the auto check but still show an error when manually checking or trying to sync.
Fixes https://github.com/UziTech/sync-settings-folder-location/issues/16
=> Wait for location service

lib/config.js, lib/location/gist.js, package-lock.json, package.json
Add a proxy setting for gist location.
defaults to `HTTPS_PROXY`, `https_proxy`, `HTTP_PROXY`, or `http_proxy` environment variable.
fixes #619
=> feat: add proxy setting

lib/main.js, lib/sync-settings.js, lib/utils/notify.js, spec/main-spec.js
Keep track of all location services provided and always use the last one. This allows switching location services when one is deactivated without needing to restart Atom.
=> fix: keep track of location services and always use last loaded
