- lib/sync-settings.coffee
> Bugfix for Hackafe/atom-sync-settings/issues/23

- lib/sync-settings.coffee
Reverts Hackafe/atom-sync-settings#35
#38 covers this and more
> Revert "Spelling Comnma to Comma"

- lib/sync-settings.coffee
> Added link to uploaded gist in success notification

- lib/sync-settings.coffee
Fixes keymap error caused by API change.
> fix keymap error

- lib/sync-settings.coffee
Refixes https://github.com/Hackafe/atom-sync-settings/pull/41
> Fix real gist url

- lib/sync-settings.coffee
- spec/sync-settings-spec.coffee
Forgot this in my last PR, had done it quickly as I only had a moment. Sorry about that.
> change keymaps for download function

- lib/sync-settings.coffee
- menus/sync-settings.cson
- spec/sync-settings-spec.coffee
Hi, I just replicated the changes I made in the previous PR, applying one minor correction that was probably among the ones that caused the impossibility to build correctly. I tested the new script on one of my installations and it doesn't seem to generate errors. Some more tests shuld be done though.
Also, minor spell checks were added.
F.
> Added default contents for empty files plus minor changes (was PR #47)

- lib/sync-settings.coffee
- spec/sync-settings-spec.coffee
> Fix writing contents to extra files

- README.md
- keymaps/sync-settings.cson
- lib/sync-settings.coffee
- menus/sync-settings.cson
- package.json
- spec/sync-settings-spec.coffee
Fixes https://github.com/Hackafe/atom-sync-settings/issues/50
> Rename Upload/Download to Backup/Restore

- .coffeelintignore
- coffeelint.json
- lib/package-manager.coffee
- lib/sync-settings.coffee
- package.json
- spec/sync-settings-spec.coffee
http://www.coffeelint.org
Should be run before submitting any new content: `coffeelint .`
> Implement CoffeeLint 

- README.md
Added some info how to run the tests to `README`.
> Add running-the-tests to README

- lib/config.coffee
- lib/sync-settings.coffee
> add config for gist description

- README.md
I think this would be clearer for how to run these commands.  At least this was how I was able to do it, if there's another way please let me know.
> Make explicit how to run sync settings commands

- lib/sync-settings.coffee
- package.json
This should address problems with proxies reported in #142.
> switch to use github4 instead of github

- lib/sync-settings.coffee
.. and show an error with what settings are missing + a button leading to the package settings if anything is missing.
> Check for mandatory settings at startup

- lib/config.coffee
- lib/sync-settings.coffee
> Ability to mute latest backup message on startup

- lib/config.coffee
- lib/sync-settings.coffee
Fixes #165. Replaces #170, simplifies the code a bit and adds an example to the config description.
> Add option blacklisting when creating a backup

- README.md
https://github.com/Hackafe/atom-sync-settings/issues/190
> Added public vs. secret gist disclaimer

- lib/sync-settings.coffee
> fix restoring color settings

- lib/sync-settings.coffee
- package.json
See https://github.com/kaizensoze/node-github/commit/a1b5014473d3849335d74ce6f141fa400d5c7902
> update dependencies, switch back to github from github4

- lib/sync-settings.coffee
> replace generic debug message with conditional error message

- lib/sync-settings.coffee
> sync available packages rather then loaded packages

- lib/sync-settings.coffee
This patch adds notifications to each package installation to provide progress information to the user. In contrast to #157 it still triggers all package installations asynchronously (which puts the system under high load but also finishes significantly faster then a sequential approach). When a package installation finishes it removes its notification (if the user hasn't dismissed it manually). At the end a final notication summaries the package installation.
> add notification while installing notifications, and final notification about the result

- lib/sync-settings.coffee
> catch SyntaxError for JSON.parse calls

- lib/tracker.coffee
> improve logic for analytics settings to avoid calling identify with invalid userId

- README.md
Seems many miss the step (including myself) to activate permissions #265
> make activate permissions bold

- lib/sync-settings.coffee
> fix restore of disabled packages

- README.md
> mention filename when creating gist

- README.md
- lib/sync-settings.coffee
> Utilise GITHUB_TOKEN env variable

- .travis.yml
Trying to check that #403 and #405 are effective.
> check with Atom beta too

- lib/sync-settings.coffee
- spec/sync-settings-spec.coffee
Replaced #383 including a spec.
Fixes #358.
> fix handling of property names with a dot

- lib/config.js
- lib/sync-settings.js
- spec/sync-settings-spec.js
> Warn about backing up config.cson

- lib/sync-settings.js
- spec/sync-settings-spec.js
> notify on Check Backup from Command Pallete

- lib/sync-settings.js
- spec/sync-settings-spec.js
* backup and restore scoped settings
* fix restoring default settings
fixes #348
fixes #289
> fix: back up settings

- lib/notify.js
- lib/sync-settings.js
- package.json
> fix: use busy-signal if available

- lib/config.js
- lib/sync-settings.js
- spec/sync-settings-spec.js
> feat: add setting to install latest version of packages

- lib/config.js
- lib/sync-settings.js
- spec/sync-settings-spec.js
> feat: add syncThemes setting

- lib/config.js
- lib/sync-settings.js
- spec/sync-settings-spec.js
> feat: add only sync community packages setting

- lib/config.js
- lib/sync-settings.js
- package-lock.json
- package.json
- spec/sync-settings-spec.js
> feat: add extra file glob settings

- lib/fork-gistid-input-view.js
- spec/fork-gistid-input-view-spec.js
> fix: fix fork gist

- lib/config.js
- lib/sync-settings.js
- spec/sync-settings-spec.js
Add "Remove Unfamiliar Files" setting to remove unfamiliar files on Backup and Restore instead of ignoring them
> Add remove unfamiliar files setting

- lib/config.js
- lib/sync-settings.js
- spec/sync-settings-spec.js
Add a setting to ignore EOL characters in diffed files
fixes #538
> fix: add ignoreEol setting

- lib/sync-settings.js
- spec/sync-settings-spec.js
> fix: display error on restore when no backup files exist

- lib/config.js
- lib/sync-settings.js
- lib/utils/notify.js
- spec/notify-spec.js
- spec/sync-settings-spec.js
Add options to auto backup/restore on startup
> feat: add autocheck dropdown setting
